<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20171120065558 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription()
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('CREATE TABLE neosrulez_blog_domain_model_category (persistence_object_identifier VARCHAR(40) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE neos_googleanalytics_domain_model_siteconfiguration DROP FOREIGN KEY FK_DACC5FD9694309E4');
        $this->addSql('DROP INDEX idx_d675f674694309e4 ON neos_googleanalytics_domain_model_siteconfiguration');
        $this->addSql('CREATE INDEX IDX_DACC5FD9694309E4 ON neos_googleanalytics_domain_model_siteconfiguration (site)');
        $this->addSql('ALTER TABLE neos_googleanalytics_domain_model_siteconfiguration ADD CONSTRAINT FK_DACC5FD9694309E4 FOREIGN KEY (site) REFERENCES neos_neos_domain_model_site (persistence_object_identifier) ON DELETE CASCADE');
        $this->addSql('DROP INDEX sourceuripathhash ON neos_redirecthandler_databasestorage_domain_model_redirect');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('DROP TABLE neosrulez_blog_domain_model_category');
        $this->addSql('ALTER TABLE neos_googleanalytics_domain_model_siteconfiguration DROP FOREIGN KEY FK_DACC5FD9694309E4');
        $this->addSql('DROP INDEX idx_dacc5fd9694309e4 ON neos_googleanalytics_domain_model_siteconfiguration');
        $this->addSql('CREATE INDEX IDX_D675F674694309E4 ON neos_googleanalytics_domain_model_siteconfiguration (site)');
        $this->addSql('ALTER TABLE neos_googleanalytics_domain_model_siteconfiguration ADD CONSTRAINT FK_DACC5FD9694309E4 FOREIGN KEY (site) REFERENCES neos_neos_domain_model_site (persistence_object_identifier) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX sourceuripathhash ON neos_redirecthandler_databasestorage_domain_model_redirect (sourceuripathhash, host)');
    }
}