-
  name: 'pagination page'
  uriPattern: '{node}/page/{page}'
  defaults:
    '@package': 'Neos.Neos'
    '@controller': 'Frontend\Node'
    '@format': 'html'
    '@action': 'show'
  routeParts:
    node:
      handler: Neos\Neos\Routing\FrontendNodeRoutePartHandlerInterface
  appendExceedingArguments: true
-
  name: 'xml format'
  uriPattern: '{node}.xml'
  defaults:
    '@package': Neos.Neos
    '@controller': Frontend\Node
    '@action': show
    '@format': xml
  routeParts:
    node:
      handler: Neos\Neos\Routing\FrontendNodeRoutePartHandlerInterface
  appendExceedingArguments: true
-
  name: 'comment'
  uriPattern: 'comment'
  defaults:
    '@controller': 'Comment'
    '@package': 'NeosRulez.Blog'
    '@action': 'create'
  appendExceedingArguments: true