Neos:
  Flow:
    mvc:
      routes:
        'NeosRulez.Blog': true
  Neos:
    userInterface:
      translation:
        autoInclude:
          NeosRulez.Blog:
            - Main
            - 'NodeTypes/*'
      defaultLanguage: 'de'
    nodeTypes:
      groups:
        blog:
          position: 'end'
          label: 'Blog'
    fusion:
      autoInclude:
        NeosRulez.Blog: true
NeosRulez:
  Blog:
    blogImageWidth: '1080'
    showAuthor: true
    showDate: true
    showSocialShare: true #Font Awesome needed
    showCategory: true
    twitterAccountName: 'yourtwittername'
    #notificationMail: 'your@mailaddress.com'