Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          NeosRulez.Blog:
            - Main
            - 'NodeTypes/*'
      defaultLanguage: 'de'
    nodeTypes:
      groups:
        blog:
          position: 'end'
          label: 'Blog'
    fusion:
      autoInclude:
        NeosRulez.Blog: true