Neos:
  Flow:
    mvc:
      routes:
        'NeosRulez.Blog': true
  Neos:
    userInterface:
      translation:
        autoInclude:
          NeosRulez.Blog:
            - Main
            - 'NodeTypes/*'
            - 'NodeTypes/Content/*'
            - 'NodeTypes/Document/*'
            - 'NodeTypes/Mixin/*'
      defaultLanguage: 'de'
    nodeTypes:
      groups:
        blog:
          position: 'end'
          label: 'Blog'
    fusion:
      autoInclude:
        NeosRulez.Blog: true
NeosRulez:
  Blog:
    showSocialShare: true
    twitterAccountName: ''
    notificationMail: ''
